
###
GET http://localhost:4000/

# Usuarios
###
GET http://localhost:4000/usuario

###
POST http://localhost:4000/usuario
Content-Type: application/json

{
    "nombre": "pepe48",
    "dni": 23323218322,
    "clave": "123456",
    "roles": "student"
}
###
GET http://localhost:4000/usuario/23323218322

##
PUT http://localhost:4000/usuario/modificarusuario/23323218322

##

DELETE http://localhost:4000/usuario/eliminarusuario/23323218322

# Comisiones
###
GET http://localhost:4000/comision

###
POST http://localhost:4000/comision
Content-Type: application/json

{
    "numero": 2157,
    "titulo": "Desarrollo Web",
    "profesor": [
      {
        "nombre": "Erica",
        "dni": "222222",
        "clave": "1234abcd",
        "roles": "admin"
      }
    ],
    "fechaInicio": "2022-03-01T00:00:00.000Z",
    "fechaFinal": "2022-10-30T03:00:00.000Z",
    "calendario": []
  }

###
PUT http://localhost:4000/comision/agregarinscripto/61ad5faa2a3c929d01ad3ea9
Content-Type: application/json

{
  "idUsuarioAInscribir":"61a8de7c2eb646572482c480",
  "rol":"admin"
}