
###
GET http://localhost:4000/

# Usuarios
###
GET http://localhost:4000/usuario

###
POST http://localhost:4000/usuario
Content-Type: application/json

{
    "nombre": "pepe44",
    "dni": 233232180,
    "clave": "123456",
    "roles": ["estudiante"]
}
